# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - @adviser/ts-xxhash

on:
  push:
  pull_request:

env:
  IN_CI: "in_ci"

jobs:
  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10

      #      - name: Patch Version ${{ env.GITHUB_REF }}
      #        run: |
      #          node ../.github/workflows/patch-package.json.js "origin/head/0.0.0-smoke"
      #          git diff
      #
      #      - name: Patch Version ${{ env.GITHUB_REF }}
      #        if: startsWith(github.ref, 'refs/tags/v')
      #        run: |
      #          node ../.github/workflows/patch-package.json.js "$GITHUB_REF"
      #          git diff

      - name: Build JS @adviser/ts-xxhash
        run: |
          pnpm install
          pnpm run format --check
          pnpm run lint
          pnpm run build
          pnpm run test
          pnpm run smoke

      - name: Publish @adviser/ts-xxhash  NPM
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd pubdir
          echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" > ~/.npmrc
          pnpm publish --access public --no-git-checks --registry https://registry.npmjs.org/

      - name: Publish @adviser/ts-xxhash  JSR
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          pnpm run deno:publish
